### ISSUE TITLE
Quick and uh. A bit too dirty.

### ISSUE THREAD

**Issue by WildCryptoFox** [bspeice/qadapt#8]
Hello. I am sorry to tell you but the Quick and Dirty Allocation Profiling Tool is just a tad bit too dirty. I have some soap.

I found QADAPT the day you [published it](https://speice.io/2018/12/allocation-safety.html) and I've been meaning to review it immediately after seeing the exposed enter and exit functions. Finally, I've reviewed your code and have [some additional test vectors for you](https://github.com/james-darkfox/qadapt-broken-tests).

> * `assert_no_alloc_then_exit_protected`: The `assert_no_alloc` macro acts like
>   `#[deny(allocations)]` but there is no way to ask to forbid allocations. Yes, a malicious
> dependency could just hook the system allocator directly.
> 
> * `no_alloc`: Works as expected. Or does it?
> 
> * `dealloc_in_no_alloc_fn`: Moving a value into a function with the `#[no_alloc]` attribute
>   incorrectly permits the deallocation of the moved value.
> 
> * `correct_dealloc_panic` and `correct_dealloc_panic2` demonstrate how that should be fixed.
> 
> * `enable_without_disable`: Entering protected mode and forgetting to exit will break the caller of
>   the offending function. There is no enforced isolation.
> 
> * `panic_on_drop_er_deadlock`: If an allocation or deallocation occurs in a drop implementation, and a panic occurs in protected mode, a double panic would happen aborting the program. Except it doesn't. Worse, the mutex hits a deadlock and the whole process hangs forever. I've disabled that test.

Fear not! I said I had soap. I've redesigned [QADAPT to fix these issues and given it a few extra features](https://gitlab.com/sio4/code/alloc-counter). I hope you don't mind.

**Comment by james-darkfox** [comment]
Spoiler: I'm currently working on getting async-fns to work, all the way down to generators that keep the allocation mode throughout their entire life, not just for their creation.

**Comment by bspeice** [comment]
I don't mind at all, your version looks amazing. I like the RAII guards far more as a design pattern, and the `#[no_alloc]` macro implementation is much cleaner. I'd love to either release it as a QADAPT 2.0, or leave a README here pointing at your version; `alloc_counter` takes the same goal of understanding allocation behavior to a new level.

There's a couple things QADAPT does that aren't currently available, but I'd be happy to submit patches for:

1. Functions marked `#[no_alloc]` should strip all allocation checking code on release builds (`debug_assert!()` style). This is done in QADAPT so that it's easy to see at a glance what's garbage-safe, while guaranteeing no run-time performance/panic impact.
2. Release mode causes issues with some tests; `-C opt-level=2` strips a lot of trivial allocations (most simple `Box<>` calls are moved to the stack), so there's a couple tests that fail with `cargo test --release` because they don't allocate the way the tests currently predict

I'm all ears for suggestions on next steps; I think your design is superior, so I'm happy to help however I can.

**Comment by WildCryptoFox** [comment]
@bspeice Thanks. BTW: I've updated it a fair bit since you checked. Now works with generators / async-await/futures and uses thread local `Cell`s instead of thread local `RefCell`s among a few other performance improving details. I'm happy with either option; but I'd like the GitLab repository to be the primary host alongside other projects that already use it (not yet published).

As I plan to use this in production code, my use is incompatible with your first suggestion. IMHO if someone wants it to only be present in debug builds, then they should use `#[cfg_attr(test, no_alloc)]` or similar. They are already responsible for `#[cfg]` flagging the `#[global_allocator]` anyway.

As for (2) nice catch. I forgot to run with `--release`! However, I'm not sure this is worth fixing - just as the doctests get annoying when you gate away the features. In most cases all features will be enabled and those who disable things will be after the fast paths in production code (I.e. only panic on allocations in certain functions; or warn on allocation load anomalies). If you can improve the tests and documentation or anything else. I'd appreciate it!

I would like to keep it simple but there is a lot of room to stream the counters out (without allocating) for external live analysis of running systems without complicating this crate too much. A unix domain socket or log file would do fine. The socket would be useful for live reconfiguration of which information should be counted.

Frequency analysis of allocation sizes and collection growing-shrinking patterns would be useful to tune reasonable real-world initial capacities.

**Comment by bspeice** [comment]
If GitLab is the primary host, I think archiving this version and putting a notice are the right things to do (once you can release `alloc_counter`). I'm currently only using QADAPT as an exploratory system, so if you have something with more practical purposes then it makes sense to focus on that for the long term.

Took a look at the recent code, and want to make sure I understand the `no_alloc` *feature*. If I understand correctly, disabling it will disable the `panic` behavior and leave in place allocation counting?

More generally, I think annotating functions with `#[cfg_attr(debug_assert, no_alloc)]` is a reasonable solution to my first point, as it still obviously says that this function is different. Would just want to make sure that's called out in the docs as a potential remedy.

I'm also reasonably sure it's worth fixing tests for `--release` mode. There may come a point in the future where this breaks because of subtle optimization differences in LLVM, but being aware of materially different behavior is part of why QADAPT was built in the first place. If you don't have a strong opinion, I'll get started on the changes.

And by next steps I was more referring to the original question of whether I should archive QADAPT, but streaming the data out sounds cool too :)

**Comment by WildCryptoFox** [comment]
@bspeice Yes that'll keep the counters and just not panic.

I've added that to the docs locally but haven't pushed it yet. How would you want the `--release` tests? Large allocations that won't get thrown on the stack?

Ah. Well, I do agree to wait for `alloc_counter` to be published first before advertising it as QADAPT's successor.

Along a similar line to the `#[no_alloc]` I've recently been informed about [`#[no-panic]`](https://docs.rs/no-panic/). This detects panic branches but only works in `--release` mode. When combined, these form a compile-time guarantee that no allocations can occur.

[I've simplified the concept to avoid the overhead of panics](https://godbolt.org/z/X75LdV), which may help the optimizer do its job better (with less code). Sadly this still requires at least `-O1` optimizations and produces a pretty ugly linker-time error on failure that doesn't say where the allocation occurred. A procedural macro can add the appropriate information into the mangled name, as `no-panic` does, but we don't need a function attribute and panics for this. Would be fun if we could register a mangled-namespace to send messages to rustc/cargo that render pretty. ;-) 

```rust
#[inline]
fn ct_assert(cond: bool) {
    if !cond {
        extern "C" { fn require_assertion_failed() -> !; }
        unsafe { require_assertion_failed() }
    }
}

pub fn main() {
    ct_assert(1 == 1);
    //ct_assert(1 == 2); // fails to compile with invalid symbol
}
```

**Comment by bspeice** [comment]
Sent two pull requests on Gitlab for release testing and docs, let me know if there are questions on those.

And compile-time allocation detection is super cool, had no idea you could get away with tricks like that in the compiler.

**Comment by bspeice** [comment]
Quick update for preserving history in the ticket: I've submitted patches for my concerns, and they've been merged. Once `alloc-counter` is available publicly, I'll update this repo to point at the new version (and close this issue).

**Comment by WildCryptoFox** [comment]
It is public, just not yet on crates.io. Any quick suggestions before I publish it?

**Comment by bspeice** [comment]
Oh, geez, I forgot to add mention of `#[cfg_attr(debug_assertions, no_alloc)]` to the docs, but otherwise no.

EDIT: Conditional compilation note added, I'm looking forward to (hopefully) taking it for a spin via crates.io in the near future.

**Comment by WildCryptoFox** [comment]
@bspeice https://docs.rs/alloc_counter/

**Comment by WildCryptoFox** [comment]
@bspeice https://www.reddit.com/r/rust/comments/anmjgs/new_crate_alloc_counter_count_allocations/

**Comment by bspeice** [comment]
Took me a bit longer than intended, but version 1.0.3 is published and we're marked deprecated. Archiving now, and excited to see where alloc-counter takes us!
